name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - riscv32imc-esp-espidf
          - xtensa-esp32-espidf

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          ldproxy: true
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --target ${{ matrix.target }} --verbose --examples
      - name: Fmt check
        run: cargo fmt --check
      - name: Clippy check
        run: cargo clippy --all-features -- -D clippy::all -W clippy::nursery
