name: Publish

on:
  workflow_dispatch

env:
  rust_toolchain: nightly

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | libncurses5
        run: sudo apt-get install libncurses5
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.3
        with:
          default: true
          ldproxy: true
      - name: Build | Publish
        run: export ESP_IDF_TOOLS_INSTALL_DIR=out; cargo publish
